version: "3"
services:
  db:
    image: postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: 123456789
      PGDATABASE: chat
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    depends_on:
      - db
      - redis
    environment:
      PGUSER: postgres
      PGHOST: db
      PGPORT: 5432
      PGPASSWORD: 123456789
      PGDATABASE: chat
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis
    ports:
      - "6379"

volumes:
  postgres-data:
